version: "3.9"

services:

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: saksham-ai
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env